version: '3.8'

services:
  web:
    build: .
    container_name: jobtrackr-web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MONGO_URI=mongodb://mongo:27017/jobtrackr
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    container_name: jobtrackr-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: